## –ü–µ—Ä–µ—Ö–æ–¥–∏–º –Ω–∞ –≥–∏–±–∫–∏–µ —Å—Ü–µ–Ω–∞—Ä–∏–∏

–ù–∞ –¥–∞–Ω–Ω—ã–π –º–æ–º–µ–Ω—Ç:

–ü—Ä–æ–ø–∏—Å–∞—Ç—å –Ω–æ—Ä–º–∞–ª—å–Ω—É—é –ª–æ–≥–∏–∫—É

–ü—Ä–æ–±–ª–µ–º—ã:

0. `convmachine.py`, —Å—Ç—Ä–æ–∫–∞ 293 ‚Äî –∫–æ–≥–¥–∞ —é–∑–µ—Ä –ø–∏—à–µ—Ç –Ω–∞–¥–æ –µ–≥–æ –∏–º—è —Ñ–∏–∫—Å–∏—Ä–æ–≤–∞—Ç—å –≤ –ë–î –ø—Ä–∞–≤–∏–ª—å–Ω–æ

1. —É –¢–µ–ª–µ–≥–∞–º–∞ –µ—Å—Ç—å –æ–ø—Ü–∏—è –æ—Ç–∑—ã–≤–∞ –≥–æ–ª–æ—Å–∞, –Ω–∞–¥–æ –µ—ë —Ä–µ–∞–ª–∏–∑–æ–≤–∞—Ç—å –Ω–∞–º –≤ –∫–æ–¥–µ –∏–Ω–∞—á–µ –ø–æ–ª—É—á–∞—é—Ç—Å—è –≥—Ä—ë–±–∞–Ω—ã–µ –¥—É–±–ª–∏

```
(<class 'IndexError'>, IndexError('list index out of range'), <traceback object at 0x1098480c0>)
Traceback (most recent call last):
  File "/Users/igor.tsupko/web/may-cat.github/eoss-bot/django-app/tbot/convmachine.py", line 250, in _basic_handler
    objStep.run(update=update, context=context, user=user)
  File "/Users/igor.tsupko/web/may-cat.github/eoss-bot/django-app/tbot/handlers/receive_poll_answer.py", line 43, in run
    answer_id = answer.option_ids[0]
IndexError: list index out of range

2022-05-30 16:47:20,051 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/igor.tsupko/web/may-cat.github/eoss-bot/django-app/tbot/convmachine.py", line 250, in _basic_handler
    objStep.run(update=update, context=context, user=user)
  File "/Users/igor.tsupko/web/may-cat.github/eoss-bot/django-app/tbot/handlers/receive_poll_answer.py", line 43, in run
    answer_id = answer.option_ids[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/igor.tsupko/web/may-cat.github/eoss-bot/django-app/tbot/convmachine.py", line 234, in _custom_poll_answer_handler
    self._basic_handler(update, context, PollAnswerHandler)
  File "/Users/igor.tsupko/web/may-cat.github/eoss-bot/django-app/tbot/convmachine.py", line 274, in _basic_handler
    self.fallbacks[FallbackToMenu]['handler'].run(update=update, context=context, user=user)
  File "/Users/igor.tsupko/web/may-cat.github/eoss-bot/django-app/tbot/handlers/menu.py", line 44, in run
    update.message.reply_text("üè† –î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å –¥–æ–º–æ–π, –≤—ã–±–µ—Ä–∏—Ç–µ –¥–µ–π—Å—Ç–≤–∏–µ:", reply_markup=markup)
AttributeError: 'NoneType' object has no attribute 'reply_text'
```

2. –ê–≤—Ç–æ—Ç–µ—Å—Ç—ã
3. –ü—Ä–æ–ø–∏—Å–∞—Ç—å —Å—Ü–µ–Ω–∞—Ä–∏–π –∑–∞–ø—Ä–æ—Å–∞ –Ω–∞ –∞–ø–ø—Ä—É–≤ –∏ –∞–ø–ø—Ä—É–≤
4. –ü—Ä–æ–ø–∏—Å–∞—Ç—å –º–µ–Ω—é —É–ø—Ä–∞–≤–ª–µ–Ω–∏—è —Å–≤–æ–∏–º–∏ –æ–±—ä–µ–∫—Ç–∞–º–∏ –Ω–µ–¥–≤–∏–∂–∏–º–æ—Å—Ç–∏
5. –ü–æ–ø—Ä–∞–≤–∏—Ç—å –æ—Ç–æ–±—Ä–∞–∂–µ–Ω–∏–µ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–æ–≤ –æ–ø—Ä–æ—Å–∞: —Ç–æ–ª—å–∫–æ –ø–æ—Å–ª–µ–¥–Ω–∏–µ 3-5